# Help: https://stackoverflow.com/questions/62783869/why-am-i-seeing-this-error-error-gcloud-run-deploy-permission-denied-the-c
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ultimate-impulse-dev/sdr-api', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ultimate-impulse-dev/sdr-api']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'sdr-api', '--image', 'gcr.io/ultimate-impulse-dev/sdr-api', '--region', 'us-central1']
images:
- gcr.io/ultimate-impulse-dev/sdr-api